#!/usr/bin/env bash

OWNER="SimplifyJobs"
REPO="Summer2026-Internships"
BRANCH="dev"
CHECK_INTERVAL=60
EMAIL="YOUR_EMAIL_HERE"

fetch_hash(){
        curl -s https://api.github.com/repos/$OWNER/$REPO/commits/$BRANCH \
                | jq -r '.sha'
}

fetch_positions(){
        curl -s https://github.com/$OWNER/$REPO \
                | grep -oP 'Software Engineering.*?\(\K\d+(?=\))' \
                | head -n 1
}

LAST_SHA=$(fetch_hash)
NUM_POSITIONS=$(fetch_positions)
while true; do
        sleep "$CHECK_INTERVAL"

        CURRENT_SHA=$(fetch_hash)

        [[ -n "$CURRENT_SHA" ]] || continue

        if [ "$CURRENT_SHA" != "$LAST_SHA" ]; then
                CURRENT_POSITIONS=$(fetch_positions)

                # If current positions is null, we can just continue
                [[ "$CURRENT_POSITIONS" =~ ^[0-9]+$ ]] || continue

                if (( CURRENT_POSITIONS  > NUM_POSITIONS )); then
                        echo "Internships increased: $NUM_POSITIONS -> $CURRENT_POSITIONS" \
                                | mail -s "New Internships!" "$EMAIL"
                fi
                NUM_POSITIONS=$CURRENT_POSITIONS
                LAST_SHA=$CURRENT_SHA
        fi
done
